name: Migrations Checker

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci

      - name: Generate Prisma (Test)
        run: npx prisma generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Check Prisma Migrations Status
        run: |
          OUTPUT=$(npx prisma migrate status)
          echo "$OUTPUT"
          if [[ $OUTPUT == *"Not applied"* ]]; then
              echo "There are pending migrations"
              exit 1
          fi
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
