name: Migration Checker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Check Prisma Migration Status
        run: |
          OUTPUT=$(npx prisma migrate status)
          echo "$OUTPUT"
          if [[ $OUTPUT == *"Not applied"* ]]; then
            echo "There are pending migrations"
            exit 1
          fi
